linters:
  enable-all: true
  disable:
    - cyclop
    - deadcode
    - depguard
    - exhaustivestruct
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gocognit
    - gocyclo
    - golint
    - ifshort
    - interfacer
    - maintidx
    - maligned
    - nlreturn
    - nosnakecase
    - scopelint
    - structcheck
    - tagliatelle
    - varcheck
    - varnamelen
    - wsl
