output:
  sort-results: true

linters:
  enable:
    - gofumpt
    - nolintlint
    - paralleltest
    - revive

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment

  errcheck:
    exclude-functions:
      - (*github.com/jackc/pgx/v5.Conn).Close

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
