linters:
  enable-all: true
  disable:
    - deadcode
    - depguard
    - exhaustivestruct
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - golint
    - ifshort
    - interfacer
    - maligned
    - noctx
    - nosnakecase
    - scopelint
    - structcheck
    - tagliatelle
    - varcheck
    - varnamelen
    - wsl
issues:
  exclude-rules:
    - path: ebay/finding.go
      text: "calculated cyclomatic complexity for function validateParams"
    - path: ebay/finding.go
      text: "Function 'validateParams' has too many statements"
    - path: ebay/finding.go
      text: "createRequest"
    - path: ebay/finding.go
      text: "calculated cyclomatic complexity for function processProductID"
    - path: ebay/finding.go
      text: "calculated cyclomatic complexity for function isValidISBN"
    - path: ebay/finding.go
      text: "handleItemFilterType"
    - path: ebay/finding.go
      text: "calculated cyclomatic complexity for function validateNumericFilter"
    - path: ebay/finding.go
      text: "calculated cyclomatic complexity for function validateListingTypes"
    - path: ebay/finding.go
      text: "calculated cyclomatic complexity for function validatePriceRange"
    - path: ebay/finding.go
      text: "calculated cyclomatic complexity for function processAffiliate"
    - path: ebay/finding.go
      text: "calculated cyclomatic complexity for function processPaginationInput"
    - path: ebay/finding.go
      text: "calculated cyclomatic complexity for function validateSortOrder"
    - path: ebay/finding_test.go
      text: "Function 'TestFindItemsAdvanced' is too long"
    - path: ebay/finding_test.go
      text: "TestFindItemsByProduct"
    - path: ebay/finding_test.go
      text: "Function 'combineTestCases' has too many statements"
    - path: ebay/finding_test.go
      text: "calculated cyclomatic complexity for function combineTestCases"
    - path: ebay/finding_test.go
      text: "testFindItems"
