issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
linters:
  enable:
    - gofumpt
    - nolintlint
    - paralleltest
    - revive
linters-settings:
  errcheck:
    exclude-functions:
      - (*github.com/jackc/pgx/v5.Conn).Close
  govet:
    disable:
      - fieldalignment
    enable-all: true
output:
  sort-results: true
