CREATE TABLE item (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    version TEXT NOT NULL,
    condition_display_name TEXT NOT NULL,
    condition_id INT NOT NULL,
    country TEXT NOT NULL,
    gallery_url TEXT,
    global_id TEXT NOT NULL,
    is_multi_variation_listing BOOLEAN NOT NULL,
    item_id BIGINT NOT NULL,
    listing_info_best_offer_enabled BOOLEAN NOT NULL,
    listing_info_buy_it_now_available BOOLEAN NOT NULL,
    listing_info_end_time TIMESTAMP WITH TIME ZONE NOT NULL,
    listing_info_listing_type TEXT NOT NULL,
    listing_info_start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    listing_info_watch_count INT,
    location TEXT,
    postal_code TEXT,
    primary_category_id BIGINT NOT NULL,
    primary_category_name TEXT NOT NULL,
    product_id_type TEXT,
    product_id_value BIGINT,
    selling_status_converted_current_price_currency TEXT,
    selling_status_converted_current_price_value NUMERIC,
    selling_status_current_price_currency TEXT,
    selling_status_current_price_value NUMERIC,
    selling_status_selling_state TEXT,
    selling_status_time_left TEXT,
    shipping_service_cost_currency TEXT,
    shipping_service_cost_value NUMERIC,
    shipping_type TEXT,
    ship_to_locations TEXT,
    subtitle TEXT,
    title TEXT NOT NULL,
    top_rated_listing BOOLEAN NOT NULL,
    view_item_url TEXT
);
